language: ruby
dist: xenial

# services:
#   - docker

# before_install:
#   -

addons:
  postgresql: 9.6
  apt:
    packages:
      - postgresql-9.6
      - postgresql-client-9.6

before_script:
  - psql -U postgres -c "create table test"

script:
  - echo "testing testing testing"
